// §2.6/2.7 — MISA 63 cột chốt GĐ1 (đồng bộ docs/ui-web.html MISA_COLS + VISIBLE_DEFAULT)
export type MisaColumn = { key: string; label: string; group: "header" | "detail" | "summary" | "extend" };

export const MISA_COLS: MisaColumn[] = [
  // Header 1-10
  { key: "ngay_ht", label: "Ngày HT", group: "header" },
  { key: "ngay_ct", label: "Ngày CT", group: "header" },
  { key: "so_ct", label: "Số CT", group: "header" },
  { key: "mst", label: "MST", group: "header" },
  { key: "ten_kh", label: "Tên KH", group: "header" },
  { key: "dia_chi", label: "Địa chỉ", group: "header" },
  { key: "dien_giai", label: "Diễn giải", group: "header" },
  { key: "ma_kh", label: "Mã KH", group: "header" },
  { key: "nhom_kh", label: "Nhóm KH", group: "header" },
  { key: "chi_nhanh", label: "Chi nhánh", group: "header" },
  // Chi tiết 11-35 (25 cột)
  { key: "ma_hang", label: "Mã hàng", group: "detail" },
  { key: "ten_hang", label: "Tên hàng", group: "detail" },
  { key: "dvt", label: "DVT", group: "detail" },
  { key: "so_luong", label: "SL", group: "detail" },
  { key: "don_gia", label: "Đơn giá", group: "detail" },
  { key: "thanh_tien", label: "Thành tiền", group: "detail" },
  { key: "thue_suat", label: "Thuế suất", group: "detail" },
  { key: "tien_thue", label: "Tiền thuế", group: "detail" },
  { key: "tk_no", label: "TK Nợ", group: "detail" },
  { key: "tk_co", label: "TK Có", group: "detail" },
  { key: "kho", label: "Kho", group: "detail" },
  { key: "so_lo", label: "Số lô", group: "detail" },
  { key: "han_sd", label: "Hạn SD", group: "detail" },
  { key: "ck_ty_le", label: "CK %", group: "detail" },
  { key: "ck_tien", label: "Tiền CK", group: "detail" },
  { key: "ngoai_te", label: "Ngoại tệ", group: "detail" },
  { key: "ty_gia", label: "Tỷ giá", group: "detail" },
  { key: "thanh_tien_qd", label: "Thành tiền QĐ", group: "detail" },
  { key: "tien_thue_qd", label: "Tiền thuế QĐ", group: "detail" },
  { key: "tk_no_qd", label: "TK Nợ QĐ", group: "detail" },
  { key: "tk_co_qd", label: "TK Có QĐ", group: "detail" },
  { key: "ghi_chu_dong", label: "Ghi chú dòng", group: "detail" },
  { key: "ma_ct_lq", label: "CT liên quan", group: "detail" },
  { key: "cp_dong", label: "CP dòng", group: "detail" },
  { key: "phi_khac", label: "Phí khác", group: "detail" },
  // Tổng hợp 36-45 (10 cột)
  { key: "tong_hang", label: "Tổng tiền hàng", group: "summary" },
  { key: "tong_thue", label: "Tổng thuế", group: "summary" },
  { key: "tong_tt", label: "Tổng TT", group: "summary" },
  { key: "tong_ck", label: "Tổng CK", group: "summary" },
  { key: "tong_cp", label: "Tổng CP", group: "summary" },
  { key: "hinh_thuc", label: "Hình thức TT", group: "summary" },
  { key: "han_tt", label: "Hạn TT", group: "summary" },
  { key: "ck_hd_ty_le", label: "CK HĐ %", group: "summary" },
  { key: "ck_hd_tien", label: "Tiền CK HĐ", group: "summary" },
  { key: "con_phai_thu", label: "Còn phải thu", group: "summary" },
  // Mở rộng 46-63 (18 cột)
  { key: "chiet_khau", label: "Chiết khấu", group: "extend" },
  { key: "cp_vc", label: "CP vận chuyển", group: "extend" },
  { key: "lo_han", label: "Lô/hạn", group: "extend" },
  { key: "ghi_chu", label: "Ghi chú", group: "extend" },
  { key: "nv_ban", label: "NV bán", group: "extend" },
  { key: "kenh", label: "Kênh", group: "extend" },
  { key: "ma_nv", label: "Mã NV", group: "extend" },
  { key: "bo_phan", label: "Bộ phận", group: "extend" },
  { key: "du_an", label: "Dự án", group: "extend" },
  { key: "hop_dong", label: "Hợp đồng", group: "extend" },
  { key: "ngay_giao", label: "Ngày giao", group: "extend" },
  { key: "dia_giao", label: "Đ/c giao", group: "extend" },
  { key: "ghi_chu_giao", label: "Ghi chú giao", group: "extend" },
  { key: "trang_thai", label: "Trạng thái", group: "extend" },
  { key: "nguon", label: "Nguồn", group: "extend" },
  { key: "external_id", label: "External ID", group: "extend" },
  { key: "last_synced", label: "Last synced", group: "extend" },
  { key: "tich_hop", label: "Tích hợp", group: "extend" },
];

export const VISIBLE_DEFAULT: string[] = [
  "so_ct",
  "ngay_ht",
  "mst",
  "ten_kh",
  "ma_hang",
  "so_luong",
  "don_gia",
  "thanh_tien",
  "thue_suat",
  "tien_thue",
  "tk_no",
  "tk_co",
];

// Sapo field → MISA column mapping (hiển thị trong modal)
export const MAPPING_ROWS: { sapo: string; misa: string; note: string }[] = [
  { sapo: "order.code", misa: "Số CT", note: "Mã đơn Sapo" },
  { sapo: "order.created_on", misa: "Ngày CT / Ngày HT", note: "Ngày chứng từ" },
  { sapo: "customer.code", misa: "MST / Mã KH", note: "Tra cứu gdt.gov.vn" },
  { sapo: "customer.name", misa: "Tên KH", note: "Tên khách hàng" },
  { sapo: "customer.address", misa: "Địa chỉ", note: "Địa chỉ giao" },
  { sapo: "line.sku", misa: "Mã hàng", note: "Map SKU → Vật tư MISA" },
  { sapo: "line.quantity", misa: "SL", note: "Số lượng" },
  { sapo: "line.price", misa: "Đơn giá / Thành tiền", note: "Giá × SL" },
  { sapo: "line.tax_rate", misa: "Thuế suất / Tiền thuế", note: "VAT 5%/8%/10%" },
  { sapo: "order.branch", misa: "Chi nhánh / Kho", note: "Q7 / Q12" },
  { sapo: "order.external_id", misa: "External ID", note: "Chống trùng ledger" },
];
