import type { CompanyLegalProfile, DocRecord } from "./types";

export const COMPANY_LEGAL_PROFILE: CompanyLegalProfile = {
  ten_doanh_nghiep: "CÔNG TY TNHH THỰC PHẨM SƠN KHANG",
  ten_tieng_anh: "SON KHANG FOODS COMPANY LIMITED",
  ten_viet_tat: "SON KHANG FOODS CO., LTD",
  mst: "0111252725",
  ngay_cap_lan_dau: "16/10/2025",
  loai_hinh: "Công ty TNHH một thành viên",
  von_dieu_le: "2.000.000.000 VNĐ",
  dia_chi_tru_so: "Thôn 6, Xã Yên Xuân, Thành phố Hà Nội, Việt Nam",
  dia_chi_kinh_doanh: "Số 96 Ngõ 337 Phố Định Công, Phường Định Công, TP. Hà Nội",
  ma_dia_diem_kd: "00001",
  nguoi_dai_dien: "HỒ BÁ THỊNH",
  chuc_danh: "Giám đốc",
  cccd: "001094016823",
  co_quan_thue: "Thuế cơ sở 22 TP. Hà Nội",
  ke_toan_thue: "TRẦN THỊ LỆ QUYÊN",
  sdt_ke_toan: "0988 000 570",
  ngan_hang: "Techcombank — STK 22226060",
  so_tai_khoan: "22226060",
  email: "thucphamsonkhang@gmail.com",
  website: "https://sonkhang.vn",
  dien_thoai: "024 22 60 60 60",
};

export const MOCK_DOCS: DocRecord[] = [
  // ── Pháp lý doanh nghiệp (5 tài liệu chính) ──
  {
    id: "DOC-LEGAL-001",
    code: "01_GCN_DKKD",
    title: "Giấy chứng nhận đăng ký doanh nghiệp — Công ty TNHH MTV",
    category: "legal",
    issuer: "Sở Tài chính TP. Hà Nội",
    issue_date: "16/10/2025",
    file_name: "01_GCN_DKKD_SON_KHANG.pdf",
    file_type: "pdf",
    file_size_kb: 384,
    storage_path: "docs/legal/01_GCN_DKKD_SON_KHANG.pdf",
    description: "GCN ĐKKD lần đầu — MST 0111252725 — Vốn điều lệ 2 tỷ — Người đại diện Hồ Bá Thịnh.",
    tags: ["ĐKKD", "MST 0111252725"],
  },
  {
    id: "DOC-LEGAL-002",
    code: "02_GCN_DKD_00001",
    title: "Giấy chứng nhận đăng ký địa điểm kinh doanh số 00001",
    category: "legal",
    issuer: "Sở Tài chính TP. Hà Nội",
    issue_date: "24/10/2025",
    file_name: "02_GCN_DKD_00001.pdf",
    file_type: "pdf",
    file_size_kb: 390,
    storage_path: "docs/legal/02_GCN_DKD_00001.pdf",
    description: "ĐĐKD 00001 — Tổng kho & trung tâm phân phối Hà Nội — Đăng ký lần đầu.",
    tags: ["ĐĐKD", "00001"],
  },
  {
    id: "DOC-LEGAL-003",
    code: "03_XAC_NHAN_DDKD",
    title: "Giấy xác nhận thay đổi nội dung ĐK hoạt động ĐĐKD & đăng ký thuế",
    category: "legal",
    issuer: "Sở Tài chính TP. Hà Nội",
    issue_date: "02/10/2026",
    file_name: "03_GIAY_XAC_NHAN_DDKD.pdf",
    file_type: "pdf",
    file_size_kb: 448,
    storage_path: "docs/legal/03_GIAY_XAC_NHAN_DDKD.pdf",
    description: "Xác nhận thay đổi địa chỉ ĐĐKD & thông tin đăng ký thuế — ĐĐKD hạch toán phụ thuộc, không nộp GTGT riêng.",
    tags: ["Thay đổi ĐĐKD", "Thuế"],
  },
  {
    id: "DOC-LEGAL-004",
    code: "04_TB_THUE",
    title: "Thông báo cơ quan thuế quản lý trực tiếp",
    category: "legal",
    issuer: "Thuế cơ sở 22 TP. Hà Nội",
    issue_date: "24/10/2025",
    file_name: "04_THONG_BAO_THUE.pdf",
    file_type: "pdf",
    file_size_kb: 440,
    storage_path: "docs/legal/04_THONG_BAO_THUE.pdf",
    description: "Thông báo phân công Thuế cơ sở 22 quản lý trực tiếp — Người phụ trách kế toán Trần Thị Lệ Quyên.",
    tags: ["Thuế", "Cơ quan quản lý"],
  },
  {
    id: "DOC-LEGAL-005",
    code: "05_DKKD_DD_L1",
    title: "Giấy CN đăng ký địa điểm kinh doanh — Thay đổi lần 1",
    category: "legal",
    issuer: "Sở Tài chính TP. Hà Nội",
    issue_date: "02/10/2026",
    file_name: "05_DKKD_DIA_DIEM_KINH_DOANH.pdf",
    file_type: "pdf",
    file_size_kb: 397,
    storage_path: "docs/legal/05_DKKD_DIA_DIEM_KINH_DOANH.pdf",
    description: "GCN ĐĐKD số 480875/26 — Địa chỉ chuẩn hóa: Số 96 Ngõ 337 Định Công, P. Định Công, Hà Nội.",
    tags: ["ĐĐKD", "Thay đổi lần 1", "96/337 Định Công"],
  },

  // ── Chứng nhận ATTP & Kiểm dịch ──
  {
    id: "DOC-CERT-001",
    code: "VSATTP-GCN-2025",
    title: "Giấy chứng nhận cơ sở đủ điều kiện VSATTP — Kho lạnh & sơ chế",
    category: "cert",
    issuer: "Chi cục An toàn VSTP — Sở Y tế Hà Nội",
    issue_date: "15/11/2025",
    file_name: "GCN_VSATTP_SON_KHANG_2025.pdf",
    file_type: "pdf",
    file_size_kb: 520,
    storage_path: "docs/legal/certs/GCN_VSATTP_SON_KHANG_2025.pdf",
    description: "Chứng nhận đủ điều kiện VSATTP cho kho lạnh Định Công & khu sơ chế — hiệu lực 3 năm.",
    tags: ["VSATTP", "Kho lạnh"],
  },
  {
    id: "DOC-CERT-002",
    code: "KD-CP-1026-01",
    title: "Chứng nhận kiểm dịch thú y lô hàng C.P. — Đợt nhập 06/10/2026",
    category: "cert",
    issuer: "Chi cục Thú y vùng — C.P. Việt Nam",
    issue_date: "06/10/2026",
    file_name: "Kiem_dich_CP_lo_20261006.pdf",
    file_type: "pdf",
    file_size_kb: 312,
    storage_path: "docs/legal/certs/Kiem_dich_CP_lo_20261006.pdf",
    description: "Phiếu kiểm dịch heo mảnh & gà ta C.P. — lô kèm PO-2026-001/PO-2026-005 — đủ điều kiện lưu thông.",
    tags: ["Kiểm dịch", "C.P.", "Lô hàng"],
  },
  {
    id: "DOC-CERT-003",
    code: "KD-VISSAN-1026-01",
    title: "Chứng nhận kiểm dịch VISSAN — Bò mát VietGAP 02/10/2026",
    category: "cert",
    issuer: "Chi cục Thú y TP.HCM — VISSAN",
    issue_date: "02/10/2026",
    file_name: "Kiem_dich_VISSAN_20261002.pdf",
    file_type: "pdf",
    file_size_kb: 298,
    storage_path: "docs/legal/certs/Kiem_dich_VISSAN_20261002.pdf",
    description: "Kiểm dịch bò mát VietGAP & heo VietGAP — kèm lô L2610-VS01/VS02 — PO-2026-006.",
    tags: ["Kiểm dịch", "VISSAN", "VietGAP"],
  },
  {
    id: "DOC-CERT-004",
    code: "VSATTP-CAM-KET-2026",
    title: "Bản cam kết VSATTP — Nhà cung cấp San Hà 2026",
    category: "cert",
    issuer: "Công ty TNHH San Hà",
    issue_date: "01/01/2026",
    file_name: "Cam_ket_VSATTP_San_Ha_2026.pdf",
    file_type: "pdf",
    file_size_kb: 185,
    storage_path: "docs/legal/certs/Cam_ket_VSATTP_San_Ha_2026.pdf",
    description: "Cam kết chất lượng & VSATTP năm 2026 — phi lê gà, mực ống, tôm sú — kèm hồ sơ NCC.",
    tags: ["VSATTP", "San Hà", "Cam kết NCC"],
  },

  // ── Hợp đồng B2B & Biểu mẫu ──
  {
    id: "DOC-TMPL-001",
    code: "HDNT-B2B-LE-2026",
    title: "Hợp đồng nguyên tắc bán lẻ thực phẩm B2B — Mẫu chuẩn",
    category: "contract_template",
    issuer: "Cty TNHH Thực phẩm Sơn Khang",
    issue_date: "01/01/2026",
    file_name: "HDNT_Ban_le_B2B_2026.docx",
    file_type: "docx",
    file_size_kb: 68,
    storage_path: "docs/legal/templates/HDNT_Ban_le_B2B_2026.docx",
    description: "Mẫu HĐ nguyên tắc bán lẻ cho quán ăn/cửa hàng — giá theo kênh, thanh toán VietQR/CK, giao chành xe.",
    tags: ["Hợp đồng", "Bán lẻ", "Mẫu"],
  },
  {
    id: "DOC-TMPL-002",
    code: "HDNT-B2B-BUON-2026",
    title: "Hợp đồng nguyên tắc bán buôn thực phẩm — Đại lý & NPP",
    category: "contract_template",
    issuer: "Cty TNHH Thực phẩm Sơn Khang",
    issue_date: "01/01/2026",
    file_name: "HDNT_Ban_buon_B2B_2026.docx",
    file_type: "docx",
    file_size_kb: 74,
    storage_path: "docs/legal/templates/HDNT_Ban_buon_B2B_2026.docx",
    description: "Mẫu HĐ bán buôn — chiết khấu theo sản lượng, công nợ 30 ngày, điều khoản FEFO & đổi trả cận date.",
    tags: ["Hợp đồng", "Bán buôn", "Đại lý"],
  },
  {
    id: "DOC-TMPL-003",
    code: "BBGN-CHANH-XE-2026",
    title: "Biên bản giao nhận hàng hóa chành xe — Mẫu ký giao",
    category: "contract_template",
    issuer: "Cty TNHH Thực phẩm Sơn Khang",
    issue_date: "01/10/2026",
    file_name: "BB_Giao_nhan_chanh_xe_2026.xlsx",
    file_type: "xlsx",
    file_size_kb: 42,
    storage_path: "docs/legal/templates/BB_Giao_nhan_chanh_xe_2026.xlsx",
    description: "Biểu mẫu biên bản giao nhận chành xe Q7/Q12 — ký nhận tài xế, đối chiếu kiện & trọng lượng.",
    tags: ["Biên bản", "Chành xe", "Giao vận"],
  },
  {
    id: "DOC-TMPL-004",
    code: "UQ-GIAO-DICH-2026",
    title: "Mẫu giấy ủy quyền giao dịch — Thu chi & nhận hàng",
    category: "contract_template",
    issuer: "Cty TNHH Thực phẩm Sơn Khang",
    issue_date: "01/01/2026",
    file_name: "Mau_Uy_quyen_giao_dich_2026.docx",
    file_type: "docx",
    file_size_kb: 38,
    storage_path: "docs/legal/templates/Mau_Uy_quyen_giao_dich_2026.docx",
    description: "Mẫu ủy quyền cho nhân sự giao dịch ngân hàng, nhận hàng NCC và ký chứng từ thay Giám đốc.",
    tags: ["Ủy quyền", "Biểu mẫu"],
  },
  {
    id: "DOC-TMPL-005",
    code: "PL-HD-BAO-GIA-2026",
    title: "Phụ lục hợp đồng — Báo giá & điều chỉnh giá theo phiên chợ",
    category: "contract_template",
    issuer: "Cty TNHH Thực phẩm Sơn Khang",
    issue_date: "01/10/2026",
    file_name: "Phu_luc_Bao_gia_2026.xlsx",
    file_type: "xlsx",
    file_size_kb: 56,
    storage_path: "docs/legal/templates/Phu_luc_Bao_gia_2026.xlsx",
    description: "Phụ lục báo giá đính kèm HĐNT — bảng giá 4 kênh, giá vốn & giá bán, áp dụng theo phiên chợ sáng.",
    tags: ["Phụ lục", "Báo giá", "Bảng giá"],
  },
];
