import type { SystemSettings } from "./types";

export const MOCK_SETTINGS: SystemSettings = {
  company: {
    legal_name: "CÔNG TY TNHH THỰC PHẨM SƠN KHANG",
    short_name: "Sơn Khang Food",
    mst: "0111252725",
    address: "Số 96 Ngõ 337 Phố Định Công, P. Định Công, Q. Hoàng Mai, TP. Hà Nội",
    warehouse_address: "Số 96 Ngõ 337 Phố Định Công, Hoàng Mai, Hà Nội — Kho trung tâm",
    hotline: "0942 22 60 60",
    tel: "(024) 22 60 60 60",
    email: "sonkhang.food@gmail.com",
    website: "https://sonkhang.vn",
    representative: "Hồ Bá Thịnh",
  },
  vietqr: {
    bank_name: "Techcombank",
    bank_code: "TCB",
    account_no: "22226060",
    account_name: "CONG TY TNHH THUC PHAM SON KHANG",
    template: "compact2",
    transfer_content_prefix: "SK",
    enabled: true,
  },
  sapo: {
    store_url: "sonkhang.mysapo.net",
    api_key_masked: "0166bd3c••••••••••••••••••••••••",
    status: "connected",
    last_synced_at: "10/10/2026 07:30",
    note: "Đồng bộ đơn hàng & tồn kho tự động",
  },
  misa: {
    amis_app_id: "SK-AMIS-2024",
    amis_status: "connected",
    meinvoice_serial: "C26TSK",
    meinvoice_template: "1/001",
    meinvoice_status: "connected",
    last_synced_at: "10/10/2026 07:00",
    note: "MISA AMIS Kế toán OpenAPI & meInvoice Bot",
  },
  policy: {
    min_order_value: 500000,
    freeship_threshold_8km: 1000000,
    freeship_threshold_12km: 3000000,
    freeship_distance_1_km: 8,
    freeship_distance_2_km: 12,
    pickup_discount_per_box: 1000,
    ageing_days: 30,
    chanh_xe_note: "Gửi chành xe bến Giáp Bát / Nước Ngầm đi các tỉnh phía Bắc",
  },
  meta: {
    version: "SK Workspace v2.1",
    db_status: "online",
    integrations_active: 4,
    integrations_total: 4,
    rbac_status: "active",
    updated_at: "10/10/2026",
  },
};
